# This is a boilerplate parameters config generated for pipeline 'compute_routes'
# using Kedro 0.19.3.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.3/configuration/parameters.html

dask:
    cluster:
        n_workers: 4
        processes: True
        threads_per_worker: 4
        memory_limit: 2GiB

graphhopper:
    image: containers/graphhopper_10.2.sif
    container_class: megaPLuG.models.routing.server.ApptainerContainerRunner
    map_path: $SCRATCH/us-latest.osm.pbf
    graph_dir: $SCRATCH/graphhopper_cache/us/
    config_path: ./conf/base/parameters_graphhopper.yml
    resources:
        import:
            mem_max_gb: 96
            mem_start_gb: 32
            startup_delay_secs: 5
        server:
            mem_max_gb: 14 # 8 is not enough to load the US, but 10 is
            mem_start_gb: 10
            startup_delay_secs: 15 # This is quite close to the shortest possible

build_dwell_id:
    col_name: dwell_id

filter_routable_dwells:
    apply_filter: True
    n_vehs: 40

get_trip_origs_and_dests:
    columns:
        hex: hex_id
        veh: veh_id
        orig: orig_point
        dest: dest_point

filter_routable_trips:
    dist_col: trip_miles
    min_dist_miles: 50

get_routes:
    profile: car
    n_trips_per_partition: 5000
    client:
        max_concurrent_requests: 20
        batch_size: 5000
        timeout_secs: 30
    input_cols:
        orig: orig_point
        dest: dest_point
    output_trip_cols:
        dist: trip_miles_route
        dur: trip_hrs_route
        speed: trip_speed_route_mph