# This is a boilerplate parameters config generated for pipeline 'compute_routes'
# using Kedro 0.19.3.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.3/configuration/parameters.html

graphhopper:
    image: containers/graphhopper_10.2.sif
    map_path: $SCRATCH/us-latest.osm.pbf
    graph_dir: $SCRATCH/graphhopper_cache/us/
    config_path: ./conf/base/parameters_graphhopper.yml
    resources:
        import:
            mem_max_gb: 96
            mem_start_gb: 32
        server:
            mem_max_gb: 32
            mem_start_gb: 16

get_routes:
    profile: car
    max_concurrent_requests: 200