"""Localised electrification probability estimation for the ``evaluate_impacts`` pipeline (Model Module 5).

Provides :class:`ElectProbLocalizer`, which fuses two probability tables to
produce a spatially localised adoption probability
``P(E | L, V)`` — the probability that a vehicle of class ``V`` operating
primarily in location class ``L`` will be electrified under a given scenario.

The two input tables are:

- **Structural table** ``P(n_electrified | n_obs, L, V)``: the observed ratio
  of electrified dwell visits to total visits for each (location class, vehicle
  class) cell in the telematics dataset.
- **Target table** ``P(E | V)``: the scenario-level adoption rate for each
  vehicle operating-distance class, drawn from the Beta-distribution/Gaussian-
  copula samples generated by the ``prepare_totals`` pipeline.
- **Weight table** ``P(L | V)``: the conditional probability that a vehicle of
  class ``V`` visits location class ``L``, estimated from the telematics data.

Algorithm (4 steps)
--------------------
1. **Fit a ridge-penalised binomial GLM** to the observed proportions
   ``n_electrified / n_obs`` for cells with ``n_obs ≥ min_obs``, using a
   Patsy formula over ``C(loc_col) + C(veh_col)`` (or a custom formula) with
   observation weights equal to ``n_obs``.
2. **Predict linear predictors** ``η̂_{L,V}`` for all (L, V) cells, including
   those below the observation threshold that were excluded from fitting.
3. **Calibrate per-vehicle offsets** ``δ_V`` by solving
   ``Σ_L P(L|V) · σ(η̂_{L,V} + δ_V) = P(E|V)`` for each vehicle class using
   Brent's method.  If the root is not bracketed, the bracket is expanded
   geometrically up to ``max_bracket_expansions`` times; if still not
   bracketed, falls back to a logit-difference approximation.
4. **Return** the calibrated probabilities
   ``P(E|L,V) = σ(η̂_{L,V} + δ_V)`` as a Series aligned with the input
   DataFrame.

Key design decisions
--------------------
- **Ridge penalty (L2)**: the GLM may be poorly conditioned when some
  (L, V) cells have very few observations.  Ridge regularisation stabilises
  the estimates without dropping cells, and the intercept is unpenalised by
  default so that the overall adoption level is unconstrained.
- **Per-vehicle calibration step**: the GLM gives a relative distribution of
  adoption across location classes, but the absolute level must match the
  scenario target ``P(E|V)``.  The additive offset ``δ_V`` shifts the logit
  uniformly across all location classes for a given vehicle class, preserving
  relative rank ordering while exactly matching the marginal target.
- **Brent's method with bracket expansion**: ``brentq`` requires a sign change
  in the objective.  For extreme target values (near 0 or 1), the default
  bracket ``[−25, +25]`` on the logit scale may be insufficient; the expansion
  loop doubles the bracket up to ``max_bracket_expansions`` times.

References
----------
Passow, F., & Rajagopal, R. (2026). Identifying indicators to inform proactive
substation upgrades for charging electric heavy-duty trucks. *Applied Energy*.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd
import patsy as pt
import statsmodels.api as sm
from scipy.optimize import brentq
from scipy.special import expit


@dataclass
class ElectProbLocalizerConfig:
    """Configuration dataclass for :class:`ElectProbLocalizer`.

    Attributes:
        loc_col: Column name for the location class (e.g. K-Means cluster ID).
            Defaults to ``"cluster_id"``.
        veh_col: Column name for the vehicle operating-distance class.
            Defaults to ``"primary_op_dist"``.
        weight_col: Column name for ``P(L|V)`` — the probability that a
            vehicle of class ``V`` visits location class ``L``.  Defaults to
            ``"p_lclass_g_vclass"``.
        n_obs_col: Column name for the total number of telematics observations
            in each ``(L, V)`` cell.  Defaults to ``"n_obs"``.
        n_electrified_col: Column name for the number of electrified
            observations in each ``(L, V)`` cell.  Defaults to
            ``"n_electrified"``.
        target_col: Column name for the scenario-level adoption rate
            ``P(E|V)``.  Defaults to ``"p_elect_g_vclass"``.
        formula: Patsy formula string for the GLM.  If ``None``, defaults to
            ``"y ~ C(loc_col) + C(veh_col)"`` (main effects only).
        ridge_lambda: L2 regularisation strength applied uniformly to all
            parameters.  Defaults to ``2.5``.
        penalize_intercept: Whether to include the intercept in the L2
            penalty.  Defaults to ``False``.
        min_obs: Minimum ``n_obs`` for a cell to be included in GLM fitting.
            Cells below this threshold still receive predictions.  Defaults to
            ``1``.
        bracket: Initial bracket half-width on the logit scale for Brent's
            root-finding.  Defaults to ``25.0``.
        max_bracket_expansions: Number of times to double the bracket before
            falling back to the logit-difference approximation.  Defaults to
            ``4``.
    """

    # Column names
    loc_col: str = "cluster_id"
    veh_col: str = "primary_op_dist"
    weight_col: str = "p_lclass_g_vclass"
    n_obs_col: str = "n_obs"
    n_electrified_col: str = "n_electrified"
    target_col: str = "p_elect_g_vclass"

    # Model config
    formula: str | None = None
    ridge_lambda: float = 2.5
    penalize_intercept: bool = False
    min_obs: int = 1

    # Calibration config
    bracket: float = 25.0
    max_bracket_expansions: int = 4


class ElectProbLocalizer:
    """Estimate localised adoption probability P(E | L, V) via GLM + per-vehicle calibration.

    Implements the four-step algorithm described in the module docstring.
    Follows a scikit-learn-style ``fit`` / ``transform`` API.

    Typical usage::

        cfg = ElectProbLocalizerConfig(loc_col="cluster_id", veh_col="primary_op_dist")
        localizer = ElectProbLocalizer(df, config=cfg)
        df["p_elect_g_vclass_loc"] = localizer.fit_transform()

    Introspection properties (available after :meth:`fit`):

    - :attr:`params_`: fitted GLM coefficient Series.
    - :attr:`eta_hat_`: linear predictor Series for all ``(L, V)`` rows.
    - :attr:`deltas_`: per-vehicle calibration offset Series.

    Args:
        df: DataFrame with one row per ``(L, V)`` cell containing all columns
            specified in ``config``.  Required columns (with default names):
            ``cluster_id``, ``primary_op_dist``, ``n_electrified``, ``n_obs``,
            ``p_lclass_g_vclass``, ``p_elect_g_vclass``.
        config: :class:`ElectProbLocalizerConfig` instance.  If ``None``,
            default column names and model settings are used.
        copy: If ``True`` (default), work on a deep copy of ``df`` to avoid
            mutating the caller's DataFrame.

    Raises:
        ValueError: If any required column is missing from ``df``, or if
            ``df`` contains ``NaN`` values in required columns.
    """

    def __init__(
        self,
        df: pd.DataFrame,
        config: ElectProbLocalizerConfig | None = None,
        copy: bool = True,
    ) -> None:
        self.config = config or ElectProbLocalizerConfig()

        # Determine required columns based on config
        cfg = self.config
        required = [
            cfg.loc_col,
            cfg.veh_col,
            cfg.n_electrified_col,
            cfg.n_obs_col,
            cfg.weight_col,
            cfg.target_col,
        ]
        missing = [c for c in required if c not in df.columns]
        if missing:
            raise ValueError(f"Input DataFrame missing required columns: {missing}")

        # NaN validation for required columns
        nan_counts = df[required].isna().sum()
        bad_nan = nan_counts[nan_counts > 0]
        if not bad_nan.empty:
            details = {col: int(cnt) for col, cnt in bad_nan.items()}
            raise ValueError(
                "NaN values detected in required columns. Clean or impute before proceeding: "
                f"{details}"
            )

        # Work on a copy to avoid mutating caller unless copy=False
        self.df = df.copy(deep=True) if copy else df
        self._fitted = False
        self._results: sm.GLM | None = None
        self._params: pd.Series | None = None
        self._eta_hat: pd.Series | None = None
        self._delta: pd.Series | None = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def fit(self) -> ElectProbLocalizer:
        """Fit the ridge-penalised binomial GLM and compute per-vehicle offsets.

        Executes steps 1–3 of the module algorithm:

        1. Subsets to rows with ``n_obs ≥ min_obs``, computes the observed
           proportion ``y = n_electrified / n_obs``, builds Patsy design
           matrices, and fits a ridge-penalised binomial GLM with
           ``var_weights = n_obs``.
        2. Predicts linear predictors for all ``(L, V)`` rows (not just those
           in the fit subset), aligning to the full DataFrame index.
        3. Calls :meth:`_compute_deltas` to solve for the per-vehicle
           calibration offset via Brent's method.

        Returns:
            ``self`` (for chaining with :meth:`transform`).

        Raises:
            ValueError: If no rows meet the ``min_obs`` threshold.
        """
        cfg = self.config
        df = self.df

        # Build working subset for fitting
        df_fit = df.loc[df[cfg.n_obs_col] >= cfg.min_obs].copy()
        if df_fit.empty:
            raise ValueError("No rows meet minimum observation threshold for fitting.")
        df_fit["y"] = df_fit[cfg.n_electrified_col].astype(float) / df_fit[
            cfg.n_obs_col
        ].astype(float)

        # Build formula dynamically if not provided
        formula = cfg.formula or f"y ~ C({cfg.loc_col}) + C({cfg.veh_col})"

        # Design matrices
        y_design, X = pt.dmatrices(formula, data=df_fit, return_type="dataframe")
        model = sm.GLM(
            y_design,
            X,
            family=sm.families.Binomial(),
            var_weights=df_fit[cfg.n_obs_col],
        )

        # Ridge penalty vector (statsmodels uses alpha for each param)
        alpha = np.full(shape=(X.shape[1],), fill_value=cfg.ridge_lambda, dtype=float)
        if not cfg.penalize_intercept and "Intercept" in X.columns:
            alpha[X.columns.get_loc("Intercept")] = 0.0

        results = model.fit_regularized(alpha=alpha, L1_wt=0.0)
        self._results = results
        self._params = results.params

        # Predict linear predictors for all rows (even those not used in fit)
        # Need to supply a dummy y to build design for the full df
        _, X_all = pt.dmatrices(formula, data=df.assign(y=0), return_type="dataframe")
        # Align columns (handle any dropped levels)
        common_cols = [c for c in results.params.index if c in X_all.columns]
        X_sel = X_all.loc[:, common_cols]
        eta_linear = results.predict(X_sel, which="linear")
        # Reindex to full DataFrame order
        eta_series = pd.Series(eta_linear, index=df.index, name="eta_hat")
        self._eta_hat = eta_series

        # Per-vehicle calibration
        delta = self._compute_deltas()
        self._delta = delta

        self._fitted = True
        return self

    def transform(self) -> pd.Series:
        """Apply the calibrated model to produce ``P(E|L,V)`` for all rows.

        Computes ``σ(η̂_{L,V} + δ_V)`` for each row, where ``δ_V`` is the
        per-vehicle offset solved by :meth:`fit`.

        Returns:
            Series named ``"p_elect_g_vclass_loc"`` with the same index as
            the input DataFrame, giving the localised electrification
            probability for each ``(L, V)`` cell.

        Raises:
            RuntimeError: If :meth:`fit` has not been called.
        """
        if not self._fitted or self._eta_hat is None or self._delta is None:
            raise RuntimeError("Call fit() before transform().")
        df = self.df
        cfg = self.config
        p = expit(self._eta_hat + self._delta.loc[df[cfg.veh_col].values].values)
        return pd.Series(p, index=df.index, name="p_elect_g_vclass_loc")

    def fit_transform(self) -> pd.Series:
        """Fit the model and immediately return transformed probabilities.

        Convenience method equivalent to ``self.fit().transform()``.

        Returns:
            Series of localised electrification probabilities (see
            :meth:`transform`).
        """
        return self.fit().transform()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _compute_deltas(self) -> pd.Series:
        """Solve for per-vehicle calibration offsets δ_V via Brent's method.

        For each vehicle class ``V``, finds the scalar ``δ_V`` such that::

            Σ_L P(L|V) · σ(η̂_{L,V} + δ_V) = P(E|V)

        Uses a symmetric bracket ``[−bracket, +bracket]`` on the logit scale,
        expanding geometrically if the root is not initially bracketed.  Falls
        back to a logit-difference approximation if expansion fails.

        Returns:
            Series indexed by vehicle class values, containing ``δ_V`` for
            each class.

        Raises:
            RuntimeError: If linear predictors have not been computed (i.e.
                :meth:`fit` has not been called).
            ValueError: If ``P(L|V)`` weights are ``NaN``, non-finite, or
                sum to zero for any vehicle class.
        """
        cfg = self.config
        df = self.df
        if self._eta_hat is None:
            raise RuntimeError("Eta (linear predictors) not computed.")

        # Group by vehicle class
        deltas = {}
        for vclass, grp in df.groupby(cfg.veh_col):
            eta_sub = self._eta_hat.loc[grp.index].values
            w_sub = grp[cfg.weight_col].values.astype(float)
            m_target = grp[cfg.target_col].iloc[0]

            # Explicit handling of NaNs or non-finite weights
            if np.isnan(w_sub).any():
                raise ValueError(
                    f"Encountered NaN weight(s) in {cfg.weight_col} for {cfg.veh_col}={vclass}. "
                    "These must be cleaned or imputed before calibration."
                )
            if (~np.isfinite(w_sub)).any():
                raise ValueError(
                    f"Encountered non-finite (inf/-inf) weight(s) for {cfg.veh_col}={vclass}."
                )
            if w_sub.sum() <= 0:
                raise ValueError(
                    f"Non-positive sum of weights for {cfg.veh_col}={vclass}. Cannot calibrate delta."
                )
            w_sub = w_sub / w_sub.sum()

            # Define root function
            def g(delta: float) -> float:
                return np.sum(w_sub * expit(eta_sub + delta)) - m_target

            # Initial bracket search
            a = -cfg.bracket
            b = cfg.bracket
            fa = g(a)
            fb = g(b)
            expansions = 0
            while fa * fb > 0 and expansions < cfg.max_bracket_expansions:
                # Expand symmetrically
                a *= 2
                b *= 2
                fa = g(a)
                fb = g(b)
                expansions += 1

            if fa * fb > 0:
                # Fallback: approximate shift via logit difference of means (approximation)
                # Compute current weighted mean probability
                p_curr = np.sum(w_sub * expit(eta_sub))
                # Stabilize extremes
                eps = 1e-8
                p_curr = np.clip(p_curr, eps, 1 - eps)
                m_t = np.clip(m_target, eps, 1 - eps)
                delta_est = np.log(m_t / (1 - m_t)) - np.log(p_curr / (1 - p_curr))
                deltas[vclass] = float(delta_est)
            else:
                try:
                    deltas[vclass] = float(brentq(g, a, b))
                except ValueError:
                    # Should not happen, but fallback to 0 shift
                    deltas[vclass] = 0.0
        return pd.Series(deltas, name="delta")

    # ------------------------------------------------------------------
    # Introspection helpers
    # ------------------------------------------------------------------
    @property
    def params_(self) -> pd.Series:
        """Fitted GLM coefficient Series.

        Raises:
            AttributeError: If :meth:`fit` has not been called.
        """
        if self._params is None:
            raise AttributeError("Model not yet fit: call fit().")
        return self._params

    @property
    def eta_hat_(self) -> pd.Series:
        """Linear predictor Series ``η̂_{L,V}`` for all (L, V) rows.

        Raises:
            AttributeError: If :meth:`fit` has not been called.
        """
        if self._eta_hat is None:
            raise AttributeError("Model not yet fit: call fit().")
        return self._eta_hat

    @property
    def deltas_(self) -> pd.Series:
        """Per-vehicle calibration offset Series ``δ_V``, indexed by vehicle class.

        Raises:
            AttributeError: If :meth:`fit` has not been called.
        """
        if self._delta is None:
            raise AttributeError("Model not yet fit: call fit().")
        return self._delta


# Example usage:
# cfg = ElectProbLocalizerConfig(loc_col="cluster_id", veh_col="primary_op_dist")
# fuser = ElectProbLocalizer(cross_cls, config=cfg)
# cross_cls["p_elect_g_vclass_lclass_cls"] = fuser.fit_transform()
